In [3]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix, accuracy_score, adjusted_rand_score, silhouette_score
import numpy as np
from scipy.stats import mode

data = {
    'Objects': ['OB-1', 'OB-2', 'OB-3', 'OB-4', 'OB-5', 'OB-6', 'OB-7', 'OB-8'],
    'X': [1, 1, 1, 2, 1, 2, 1, 2],
    'Y': [4, 2, 4, 1, 1, 4, 1, 1],
    'Z': [1, 2, 2, 2, 1, 2, 2, 1],
    'True_Label': [0, 1, 0, 2, 1, 0, 1, 2]
}

def map_clusters_to_labels(true_labels, clusters):
    labels = np.zeros_like(clusters)
    for i in range(3):
        mask = (clusters == i)
        labels[mask] = mode(true_labels[mask])[0]
    return labels

In [4]:
df = pd.DataFrame(data)
X = df[['X', 'Y', 'Z']]
kmeans = KMeans(n_clusters=3, random_state=21)
kmeans.fit(X)
df['Cluster'] = kmeans.predict(X)

mapped_clusters = map_clusters_to_labels(df['True_Label'].values, df['Cluster'].values)

conf_matrix = confusion_matrix(df['True_Label'], mapped_clusters)
accuracy = accuracy_score(df['True_Label'], mapped_clusters)
ari = adjusted_rand_score(df['True_Label'], df['Cluster'])
silhouette = silhouette_score(X, df['Cluster'])

In [5]:
print("Confusion Matrix:")
print(conf_matrix)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Adjusted Rand Index (ARI): {ari:.2f}")
print(f"Silhouette Score: {silhouette:.2f}")

Confusion Matrix:
[[3 0 0]
 [0 3 0]
 [0 2 0]]
Accuracy: 75.00%
Adjusted Rand Index (ARI): 0.36
Silhouette Score: 0.38
